spring.application.name=GWConnector
# allow Render (or other PaaS) to set the port via PORT env var
server.port=${PORT:8081}
policy-api.url=https://pc-dev-gwcpdev.valuemom.zeta1-andromeda.guidewire.net/rest/policy/v1/search/policies
policy-api.username=su
policy-api.password=gw
claim-api.url=https://cc-dev-gwcpdev.valuemom.zeta1-andromeda.guidewire.net
admin-api.url=https://cc-dev-gwcpdev.valuemom.zeta1-andromeda.guidewire.net
